Attempt to accumulate output
There seems to be a race between the termination handler and the readability
handler. This is causing the printf test to flicker.

Passing output looks like:

    Test Case '-[AdianTests.FoundationTaskTests testDeliversStandardOutputWhenInvokedWithPrintf]' started.
    2015-12-06 22:40:02.751 Adian[12388:18016054] READING!
    2015-12-06 22:40:02.884 Adian[12388:18016176] CALLED!
    2015-12-06 22:40:02.884 Adian[12388:18016176] read 7 bytes
    2015-12-06 22:40:02.884 Adian[12388:18016177] TERMINATED!
    Test Case '-[AdianTests.FoundationTaskTests testDeliversStandardOutputWhenInvokedWithPrintf]' passed (0.226 seconds).

Failing looks like:

    Test Case '-[AdianTests.FoundationTaskTests testDeliversStandardOutputWhenInvokedWithPrintf]' started.
    2015-12-06 22:41:41.189 Adian[12725:18025128] READING!
    2015-12-06 22:41:41.191 Adian[12725:18025262] CALLED!
    2015-12-06 22:41:41.191 Adian[12725:18025265] TERMINATED!
    2015-12-06 22:41:41.192 Adian[12725:18025262] read 7 bytes
    FoundationTaskTests.swift:36: error: -[AdianTests.FoundationTaskTests testDeliversStandardOutputWhenInvokedWithPrintf] : XCTAssertEqual failed: ("Optional("")") is not equal to ("Optional("howdy!\n")") -
    Test Case '-[AdianTests.FoundationTaskTests testDeliversStandardOutputWhenInvokedWithPrintf]' failed (0.005 seconds).